export { default as Banner } from "./Banner";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as Products } from "./Products";
export { default as Services } from "./Services";
export { default as SubBanner } from "./SubBanner";
export { default as Testimonials } from "./Testimonials";
export { default as Work } from "./Work";
